/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package companymanagementsystem;

import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EXCALIBUR
 */
public class AdminPage extends javax.swing.JFrame {

    Connections connections = new Connections();

    private void updateTable(String tableName) {
        try {
            List<Object[]> rowDataList = connections.fetchRowObjects(tableName);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Tabloyu temizle
            for (Object[] rowData : rowDataList) {
                model.addRow(rowData);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Creates new form AdminPanelPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminCombobox = new javax.swing.JComboBox<>();
        adminInsertButton = new javax.swing.JButton();
        adminDeleteButton = new javax.swing.JButton();
        adminUpdateButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        adminColumn1 = new javax.swing.JLabel();
        adminColumn2 = new javax.swing.JLabel();
        adminColumn3 = new javax.swing.JLabel();
        columnArea1 = new javax.swing.JTextField();
        columnArea2 = new javax.swing.JTextField();
        columnArea3 = new javax.swing.JTextField();
        adminErrorMessage = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("ADMIN PANEL");

        adminCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEFAULT", "ADMIN", "EMPLOYEES", "PRODUCTS" }));
        adminCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminComboboxActionPerformed(evt);
            }
        });

        adminInsertButton.setText("INSERT");
        adminInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInsertButtonActionPerformed(evt);
            }
        });

        adminDeleteButton.setText("DELETE");
        adminDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDeleteButtonActionPerformed(evt);
            }
        });

        adminUpdateButton.setText("UPDATE");
        adminUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUpdateButtonActionPerformed(evt);
            }
        });

        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1", "2", "3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(adminTable);

        adminColumn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminColumn1.setText("Column 1 ");

        adminColumn2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminColumn2.setText("Column 2");

        adminColumn3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminColumn3.setText("Column 3");

        columnArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnArea3ActionPerformed(evt);
            }
        });

        adminErrorMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adminErrorMessage.setForeground(new java.awt.Color(204, 0, 0));
        adminErrorMessage.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adminDeleteButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(adminColumn1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(adminColumn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(adminColumn3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(columnArea1)
                                    .addComponent(columnArea2)
                                    .addComponent(columnArea3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGap(93, 93, 93)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminUpdateButton)
                                    .addComponent(adminInsertButton)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(adminCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminColumn1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(columnArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminInsertButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminColumn2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(columnArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminDeleteButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminColumn3)
                    .addComponent(columnArea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminUpdateButton))
                .addGap(26, 26, 26)
                .addComponent(adminErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminComboboxActionPerformed
        try {
            String tableName = String.valueOf(adminCombobox.getSelectedItem());

            String[] columnNames = connections.getColumnNames(tableName);
            List<Object[]> rowDataList = connections.fetchRowObjects(tableName); // Verileri çek

            DefaultTableModel model = new DefaultTableModel();
            for (String columnName : columnNames) {
                model.addColumn(columnName); // Her bir sütun ismini modele ekle
            }
            adminColumn1.setText(columnNames[0]);
            adminColumn2.setText(columnNames[1]);
            adminColumn3.setText(columnNames[2]);

            for (Object[] rowData : rowDataList) {
                model.addRow(rowData); // Her bir satýrý modele ekle
            }

            jTable1.setModel(model); // Tabloya modeli ekle
            jScrollPane2.setViewportView(jTable1);

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_adminComboboxActionPerformed

    private void columnArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnArea3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnArea3ActionPerformed

    private void adminInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInsertButtonActionPerformed
        try {
            String selectedTable = String.valueOf(adminCombobox.getSelectedItem());
            String[] columnNames = connections.getColumnNames(selectedTable);

            String[] values = new String[3]; // veya gerekli sayýda elemanlý bir dizi
            values[0] = columnArea1.getText();
            values[1] = columnArea2.getText();
            values[2] = columnArea3.getText();

            connections.insertData(selectedTable, columnNames, values);

            adminErrorMessage.setText(" NEW " + selectedTable + " SUCCESSFULLY INSERTED TO THE TABLE !");
            columnArea1.setText("");
            columnArea2.setText("");
            columnArea3.setText("");

            updateTable(selectedTable);

        } catch (Exception ex) {
            adminErrorMessage.setText("INSERT ATTEMPT FAILED !!!");
        }
    }//GEN-LAST:event_adminInsertButtonActionPerformed

    private void adminUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUpdateButtonActionPerformed

        adminErrorMessage.setText("");
        int selectedRowIndex = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object primaryKeyValue = jTable1.getValueAt(selectedRowIndex, 0);
        String primaryKeyValueAsString = primaryKeyValue.toString();
        // Seçilen satýrýn indexini al

        if (selectedRowIndex == -1) {
            if (adminTable.getRowCount() == 0) {
                adminErrorMessage.setText("Table is Empty...");
            } else {
                adminErrorMessage.setText("Please click on a row to Update");
            }

        } else {

            try {
                adminErrorMessage.setText("");

                if (selectedRowIndex == -1) {
                    if (adminTable.getRowCount() == 0) {
                        adminErrorMessage.setText("Table is Empty...");
                    } else {
                        adminErrorMessage.setText("Please click on a row to Update");
                    }
                } else {
                    String tableName = String.valueOf(adminCombobox.getSelectedItem());

                    String newValue1 = columnArea1.getText();
                    String newValue2 = columnArea2.getText();
                    String newValue3 = columnArea3.getText();

                    // Seçilen satýrýn özgün deðerleri
                    model.getValueAt(selectedRowIndex, 0).toString();

                    // Yeni deðerleri güncelleme metoduna iletiyoruz
                    String[] columnNames = {model.getColumnName(0), model.getColumnName(1), model.getColumnName(2)}; // Sütun isimleri
                    String[] newValues = {newValue1, newValue2, newValue3}; // Yeni deðerler
                    String primaryKeyColumnName = jTable1.getColumnName(0); // Primary key sütun adý

                    connections.updateData(tableName, columnNames, newValues, primaryKeyColumnName, primaryKeyValueAsString);

                    // Tabloyu güncelle
                    updateTable(tableName);

                    // Text field'larý sýfýrla
                    columnArea1.setText("");
                    columnArea2.setText("");
                    columnArea3.setText("");
                }
            } catch (Exception exx) {
                System.out.println(exx);
            }
        }
    }//GEN-LAST:event_adminUpdateButtonActionPerformed

    private void adminDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDeleteButtonActionPerformed
        String primaryKeyColumnName = jTable1.getColumnName(0);
        String tableName = String.valueOf(adminCombobox.getSelectedItem());
        int selectedRowIndex = jTable1.getSelectedRow();
        Object primaryKeyValue = jTable1.getValueAt(selectedRowIndex, 0);
        String primaryKeyValueAsString = primaryKeyValue.toString();
        if (selectedRowIndex != -1) {

            connections.deleteRow(tableName, primaryKeyColumnName, primaryKeyValueAsString);

            // Swing tablonuzu güncellemeyi unutmayýn
            updateTable(tableName);
        } else {
            // Kullanýcý bir satýr seçmediðinde bir hata mesajý gösterebilirsiniz.
        }

    }//GEN-LAST:event_adminDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminColumn1;
    private javax.swing.JLabel adminColumn2;
    private javax.swing.JLabel adminColumn3;
    private javax.swing.JComboBox<String> adminCombobox;
    private javax.swing.JButton adminDeleteButton;
    private javax.swing.JLabel adminErrorMessage;
    private javax.swing.JButton adminInsertButton;
    private javax.swing.JTable adminTable;
    private javax.swing.JButton adminUpdateButton;
    private javax.swing.JTextField columnArea1;
    private javax.swing.JTextField columnArea2;
    private javax.swing.JTextField columnArea3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
